# Generated by Django 5.2.9 on 2026-05-14 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0009_merge_20260320_1253'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_name', models.CharField(max_length=100)),
                ('welcome_message', models.TextField(help_text='The first message the bot sends when the chat opens')),
                ('system_prompt', models.TextField(help_text="The full system prompt that defines the bot's knowledge and behaviour")),
                ('message_limit', models.PositiveIntegerField(default=200, help_text='Maximum number of messages a user can send')),
                ('access_days', models.PositiveIntegerField(default=60, help_text='Number of days access is granted after purchase')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bot', to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='BotAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('access_expires', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_accesses', to=settings.AUTH_USER_MODEL)),
                ('bot_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='bots.botproduct')),
            ],
            options={
                'verbose_name_plural': 'Bot Accesses',
                'unique_together': {('user', 'bot_product')},
            },
        ),
    ]
