# Generated by Django 5.2.9 on 2026-05-14 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.JSONField(default=list, help_text='Full conversation history as a list of role/content dicts')),
                ('quiz_answers', models.JSONField(blank=True, default=dict, help_text='Stored quiz question and answer pairs')),
                ('saved_goal', models.TextField(blank=True, help_text='The goal text the user chose to save to the tracker')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bot_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='bots.botproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bot Conversations',
                'unique_together': {('user', 'bot_product')},
            },
        ),
    ]
