# Generated by Django 5.2.9 on 2026-05-14 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_botconversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Momentum Your Way Workbook', max_length=100)),
                ('knowledge_file', models.FileField(help_text='PDF file only', upload_to='bot_knowledge/')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Order in which files are added to the prompt')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bot_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_files', to='bots.botproduct')),
            ],
            options={
                'ordering': ['order', 'created'],
            },
        ),
    ]
