# Generated by Django 5.2.9 on 2026-05-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_botknowledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='botaccess',
            name='bonus_messages',
            field=models.PositiveIntegerField(default=0, help_text='Extra messages granted manually (e.g. top-up purchases)'),
        ),
    ]
