# Generated by Django 5.2.9 on 2026-05-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_botaccess_bonus_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botproduct',
            name='access_days',
            field=models.PositiveIntegerField(default=60, help_text='Number of days access is granted after purchase (60 for individual, 90 for bundles)'),
        ),
        migrations.AlterField(
            model_name='botproduct',
            name='message_limit',
            field=models.PositiveIntegerField(default=50, help_text='Maximum number of messages a user can send (50 for individual, 150 for bundles)'),
        ),
    ]
