# Generated by Django 5.2.14 on 2026-05-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_updated',
            field=models.DateTimeField(blank=True, help_text='Set this manually when you make a meaningful content change. Used for dateModified in schema — do not update for admin-only saves.', null=True),
        ),
    ]
