# Generated by Django 5.2.9 on 2026-07-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_writing_default_lillol_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_type',
            field=models.CharField(choices=[('article', 'Writing'), ('alive', 'Alive List'), ('bite', 'Bites — short quick-read'), ('video', 'Video'), ('audio', 'Audio / Podcast')], default='article', help_text='The FORMAT of the post: Writing = standard post (default), ALIVE List = short and playful, Bites = short quick-read, Video = video embed, Audio = podcast/audio embed. Use Tags below for TOPICS like Choices or Updates.', max_length=10),
        ),
    ]
