# Generated by Django 5.2.4 on 2025-07-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingsession',
            name='prompt_used',
            field=models.TextField(blank=True, null=True),
        ),
    ]
