# Generated by Django 5.2.4 on 2025-07-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0002_alter_writingsession_prompt_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='promptcategory',
            name='sub_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='writingprompt',
            name='writing_styles',
            field=models.ManyToManyField(blank=True, related_name='prompts', to='prompt.writingstyle'),
        ),
    ]
