# Generated by Django 5.2.4 on 2025-07-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0003_writingstyle_promptcategory_sub_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingprompt',
            name='prompt_type',
            field=models.CharField(choices=[('journal', 'Journal Entry'), ('memoir', 'Memoir/Memory'), ('both', 'Both')], default='journal', max_length=15),
        ),
    ]
