# Generated by Django 5.2.4 on 2025-07-24 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0004_alter_writingprompt_prompt_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='writinggoal',
            name='goal_label',
            field=models.CharField(blank=True, help_text='Optional custom label (e.g., Read 10 pages, Drink water)', max_length=100),
        ),
        migrations.AlterField(
            model_name='writinggoal',
            name='goal_type',
            field=models.CharField(choices=[('time', 'Minutes per session'), ('words', 'Words per session'), ('sessions', 'Number of sessions')], default='time', help_text='Used for tracking writing progress', max_length=10),
        ),
        migrations.AlterField(
            model_name='writinggoal',
            name='target_value',
            field=models.PositiveIntegerField(help_text='Target value (e.g., 30 minutes, 10 sessions, 1000 words)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
