# Generated by Django 5.2.4 on 2025-08-13 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0005_writinggoal_goal_label_alter_writinggoal_goal_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingsession',
            name='goal',
            field=models.ForeignKey(help_text='Which goal is this session for?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='prompt.writinggoal'),
        ),
    ]
