# Generated by Django 5.2.4 on 2025-08-13 17:33

from django.db import migrations


def delete_null_goal_sessions(apps, schema_editor):
    WritingSession = apps.get_model("prompt", "WritingSession")
    WritingSession.objects.filter(goal__isnull=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("prompt", "0006_writingsession_goal"),
    ]

    operations = [
        migrations.RunPython(delete_null_goal_sessions, migrations.RunPython.noop),
    ]
