# Generated by Django 5.2.4 on 2025-08-13 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0007_clean_null_goal_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingsession',
            name='minutes_spent',
            field=models.PositiveIntegerField(blank=True, help_text='How many minutes did you spend on your goal?', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
