# Generated by Django 5.2.4 on 2025-08-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0008_alter_writingsession_minutes_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writinggoal',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Day'), ('weekly', 'Week'), ('monthly', 'Month')], default='daily', max_length=10),
        ),
    ]
