# Generated by Django 5.2.4 on 2025-09-03 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0009_alter_writinggoal_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingsession',
            name='goal',
            field=models.ForeignKey(help_text='Which goal is this session for?', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='prompt.writinggoal'),
        ),
    ]
