# Generated by Django 5.2.9 on 2026-04-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_memberresource_options_memberresource_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_subscribed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mailerlite_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
