# Generated by Django 5.2.9 on 2026-08-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_oto_seen_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailListStatsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, default='', max_length=20)),
                ('subscribers_total', models.PositiveIntegerField(blank=True, null=True)),
                ('new_last_30d', models.PositiveIntegerField(blank=True, null=True)),
                ('growth_pct', models.FloatField(blank=True, null=True)),
                ('ok', models.BooleanField(default=False)),
                ('error', models.CharField(blank=True, default='', max_length=100)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email List Stats Snapshot',
                'verbose_name_plural': 'Email List Stats Snapshot',
            },
        ),
    ]
