# Generated by Django 5.2.4 on 2025-11-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_video_file_product_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('download', 'Digital Download')], default='download', max_length=20),
        ),
    ]
