# Generated by Django 5.2.9 on 2026-03-20 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_orderitem_downloads_remaining_downloadlog'),
        ('shop', '0008_alter_product_product_type'),
    ]

    operations = [
    ]
