# Generated by Django 5.2.9 on 2026-06-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, help_text='Percentage (e.g. 10 for 10%) or fixed amount in pounds (e.g. 5 for £5).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='minimum_order_pence',
            field=models.PositiveIntegerField(default=0, help_text='Minimum cart total (in pence) required for this coupon.'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Max total uses. Leave blank for unlimited.', null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='currency_code',
            field=models.CharField(choices=[('GBP', 'British Pound (£)'), ('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)')], default='GBP', max_length=3, verbose_name='Currency Code'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='currency_symbol',
            field=models.CharField(default='£', max_length=5, verbose_name='Currency Symbol'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_app_id',
            field=models.CharField(blank=True, default='', help_text='Facebook App ID for Open Graph fb:app_id tag.', max_length=50, verbose_name='Facebook App ID'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, default='', help_text='Google Analytics measurement ID, e.g. G-XXXXXXXXXX.', max_length=30, verbose_name='Google Analytics ID'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='google_search_console_verification',
            field=models.CharField(blank=True, default='', help_text='Verification token from Google Search Console meta tag.', max_length=255, verbose_name='GSC Verification Token'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Default Open Graph image (1200x630 px recommended).', null=True, upload_to='site/og/', verbose_name='Default OG Image'),
        ),
    ]
