# Generated by Django 5.2.9 on 2026-06-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_onetimeoffer_included_products'),
        ('tools', '0004_hostedtool'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hosted_tool',
            field=models.OneToOneField(blank=True, help_text="Optional: attach a Hosted Tool to sell it as this product. Buyers reach the live tool from their downloads area, and the tool's public page becomes purchase-only. Leave blank for a normal file download.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='tools.hostedtool'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('download', 'Digital Download'), ('tool', 'Hosted Tool')], default='download', max_length=20),
        ),
    ]
