# Generated by Django 5.2.9 on 2026-06-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_product_hosted_tool_alter_product_product_type'),
        ('tools', '0005_hostedtool_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hosted_tool',
            field=models.OneToOneField(blank=True, help_text="Optional: attach a Hosted Tool to sell it as this product. Only tools set to 'Paid' can be selected here. Buyers reach the live tool from their downloads area, and the tool's public page becomes purchase-only. Leave blank for a normal file download.", limit_choices_to={'access': 'paid'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='tools.hostedtool'),
        ),
    ]
