# Generated by Django 5.2.9 on 2026-09-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_productknowledge_productquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productknowledge',
            name='target_audience',
            field=models.TextField(blank=True, help_text="The specific kind of person this is for, not 'everyone'.", verbose_name="Who it's for"),
        ),
    ]
