# Generated by Django 5.2.9 on 2026-06-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone', models.CharField(choices=[('30', '30 Days'), ('60', '60 Days'), ('90', '90 Days')], max_length=2)),
                ('goal_text', models.CharField(max_length=200)),
                ('is_achieved', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['milestone', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ExperimentWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_date', models.DateField(help_text='The Monday this week starts', unique=True)),
                ('week_number', models.PositiveIntegerField()),
                ('is_milestone', models.BooleanField(default=False)),
                ('milestone_label', models.CharField(blank=True, max_length=50, null=True)),
                ('blog_posts_rewritten', models.PositiveIntegerField(default=0)),
                ('pinterest_pins', models.PositiveIntegerField(default=0)),
                ('youtube_audio', models.PositiveIntegerField(default=0)),
                ('substack_posts', models.PositiveIntegerField(default=0)),
                ('emails_added', models.PositiveIntegerField(default=0)),
                ('ga4_sessions', models.PositiveIntegerField(blank=True, null=True)),
                ('what_i_did', models.TextField(blank=True)),
                ('what_i_noticed', models.TextField(blank=True)),
                ('what_changed', models.TextField(blank=True)),
                ('went_well_wednesday', models.TextField(blank=True)),
                ('revenue_this_week', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('transactions', models.PositiveIntegerField(default=0)),
                ('email_list_total', models.PositiveIntegerField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-week_date'],
            },
        ),
        migrations.CreateModel(
            name='MilestoneReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone', models.CharField(choices=[('30', '30 Days'), ('60', '60 Days'), ('90', '90 Days')], max_length=2, unique=True)),
                ('reflection_text', models.TextField()),
                ('published_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
