# Generated by Django 5.2.9 on 2026-06-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_hostedtool'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostedtool',
            name='access',
            field=models.CharField(choices=[('free', 'Free — anyone can use it'), ('paid', 'Paid — only buyers can use it')], default='free', help_text="Free tools are public at /tools/<slug>/. Paid tools are unlocked only by buying a linked shop product (attach this tool to a Product in the shop, then it appears in the buyer's downloads area).", max_length=10),
        ),
    ]
