# Generated by Django 5.2.9 on 2026-06-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_hostedtool_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostedtool',
            name='link_text',
            field=models.CharField(blank=True, help_text="Optional. The clickable label for a link button shown at the top AND bottom of the tool's page (e.g. 'Back to the shop', 'Get the full guide'). Leave blank to hide the link.", max_length=120, verbose_name='URL name'),
        ),
        migrations.AddField(
            model_name='hostedtool',
            name='link_url',
            field=models.URLField(blank=True, help_text='Where the link button points. Only shown if both fields are filled.', max_length=500, verbose_name='URL link'),
        ),
    ]
