# Generated by Django 5.2.9 on 2026-09-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_toolsavedresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostedtool',
            name='og_image',
            field=models.ImageField(blank=True, help_text="Image shown when this tool's page is shared (social previews, Benable, etc.), 1200x630 px recommended. Leave blank to use the site's default image.", null=True, upload_to='tools/og/', verbose_name='Social Preview Image'),
        ),
    ]
